### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by YouthLin** [Michael-Sui/IMServer#1]
既然 README 里写了可以发表评论，那就写一点点拙见，希望大佬不要介意

IMServer/server/Database.java
SQL语句用加号拼接有注入风险；

尽量不要使用 `System.out/System.err`，更不要使用 `e.printStackTrace();` 换成 Log(如 SLF4J)；

为啥不用 Maven 呢，包目录组织就一级感觉怪怪的……

没有参数校验；

用了许多 public static 属性，导致不够面向对象；

Server.java#init() 同时只能有一个用户登录？而且只要有一个用户出错了服务器就挂了？

**Comment by Michael-Sui** [comment]
感谢您肯花时间看我写的代码还提出了修改意见，谢谢。
【1】关于SQL注入风险，已经由Statement改为PrepareStatement。
【2】关于日志的问题。。。确实使用out、err显得有些奇怪，但是不得不说有时候简单查看下变量的值还是挺方便的，实际使用（交作业）时这些out、err肯定是要删掉的。以后尽量改正吧。
【3】Maven。。。没用过，下周有空了解下。。。(⊙﹏⊙)b
【4】参数校验会在后期加上，现在着急实现功能，所以暂时没加。
【5】static确实不好，已经删掉了一部分。
【6】服务器只有一个，监听10001端口，但是可以有多个客户端访问，建立多个线程。暂时没发现服务器挂的现象，但是会有资源浪费的现象，正在思考解决方案。
